### ISSUE TITLE
🐞 Bug: Light Theme checkmarks invisible.

### ISSUE THREAD

**Issue by NeoCortex3** [getarcaneapp/arcane#1045]
### Bug Description

When selecting the light theme, checkmarks inside checkboxes are invisble as they are white font on white background.

var(--primary-foregound) needs to be black when the light theme is selected. By the love of god I can't figure out where in the CSS it's defined.

### Steps To Reproduce

1. Select the light theme
2. Goto any page that has checkboxes.
3. Note that checkboxes which are checked just have the border but not a checkmark.

### Expected Behavior

Have a visible checkmark when a checkbox is checked

### Actual Behavior

You won't see a checkmark

### Screenshots

<img width="913" height="522" alt="Image" src="https://github.com/user-attachments/assets/f1d3e29e-d23d-44a3-a683-41eb220c7a9a" />

### Arcane Version

v1.10.0

### Operating System

Linux

### Browser

Firefox 145.0.2

### Docker Version

Docker version 29.1.1, build 0aedba5

**Comment by kmendell** [comment]
Thanks :)

Fixed it here: https://github.com/getarcaneapp/arcane/commit/ff67565b1def18da4bb937d633911264ddbcce98

**Comment by NeoCortex3** [comment]
ahh so in the css :root is the light theme and .dark the dark one.
thats why I couldn't find "light" in den app.css

**Comment by mguilherme** [comment]
it seems that the issue still occurs with the new version

<img width="2388" height="1426" alt="Image" src="https://github.com/user-attachments/assets/fb971fc1-e0ea-46ee-99b0-f720aef13434" />

**Comment by mguilherme** [comment]
@kmendell updated today to v1.11.1 and the issue persist, should I open another issue?
