### ISSUE TITLE
🐞 Bug: Existing Projects not Discovered

### ISSUE THREAD

**Issue by languagegame** [getarcaneapp/arcane#695]
### Bug Description

Arcane does not discover existing docker compose projects in my projects folder upon a new installation.  Arcane creates new projects correctly, but it does not find existing projects.

### Steps To Reproduce

1) I have a folder for existing compose projects at /volume1/docker with a subfolder for each project.  Each subfolder contains a docker-compose.yaml and an .env file.  /volume1/docker is owned by root:root and each subfolder is owned by username:users
2) I install arcane using docker compose.  I mount my projects directory into the container using the same absolute path inside of the container as my host
```
volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - ./data/:/app/data/
  - /volume1/docker/:/volume1/docker/
environment:
  - PUID=1000 # username is non-root user
  - PGID=100   # users is non-root
```
3) During the initial setup of arcane, I set Projects Directory = /volume1/docker/

None of my existing projects are discovered by Arcane in the projects directory.
If I then create a new project using Arcane called "test1", the subfolder shows up correctly in /volume1/docker/test1 in the container and on the host.
If I copy that test1 folder to /volume1/docker/test2 to simulate an existing project and restart Arcane, Arcane does not see test2 project.  it only sees the test1 project that it created originally.  Both test and test2 folders are in /volume/docker with same permissions.
If I remove Arcane from my machine (including its database) and reinstall Arcane from scratch, the new Arcane does not see test1 or test 2.  This is odd as the prior version created test1

### Expected Behavior

Arcane should discover all my existing docker compose projects in my project folder.

### Actual Behavior

Arcane does not discover exiting projects.  It does not discover existing projects even if created by a prior installation of Arcane.  It also does not discover existing projects created manually outside of arcane in the same projects folder.

If I have the PUID and PGID set in the docker compose for arcane, I see a permission denied entry in the DEBUG log which looks like the user/group does not have enough permission to the /volume/docker folder.
The log file shows
```
Oct 12 17:25:07.574 INF Filesystem watcher job registered
Oct 12 17:25:07.574 INF Starting scheduler
Oct 12 17:25:07.574 INF Starting job scheduler
Oct 12 17:25:07.574 INF Starting HTTP server port=3552
Oct 12 17:25:07.574 DBG SQL query executed [342.134µs] query="SELECT * FROM `settings`" duration=342.134µs rows=24 file=github.com/ofkm/arcane-backend/internal/services/settings_service.go:244
Oct 12 17:25:07.574 ERR Filesystem watcher failed error="permission denied"
```
However, if I then remove the PUID and PGID from the container entirely and restart it, Arcane's dashboard shows this error when I go to the "Projects" tab:
`Something went wrong, Internal error 500` with a link to "Go to Dashboard".   

### Arcane Version

v1.5.1

### Operating System

Linux

### Browser

Chome

### Docker Version

26.1.0

**Comment by weedy** [comment]
Do you have anything else going on that going to make permissions a problem?
ACL? SElinux?

Even with my shitty NAS, after I got permissions correct I've had 0 problems.

```
    environment:
<skip the rest>
      # Optional: Set if Docker access fails
      - DOCKER_GID=0
      # Optional: Match your host user for permissions
      - PUID=1001
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /share/docker/appdata/arcane/config:/app/data
      - /share/docker/compose:/app/data/templates
      - /share/docker/stacks:/app/data/projects
```
```
]# ls -al /share/docker/
drwxrwx---    9 1001     1000             9 Jul 27 13:10 .
drwxr-xr-x    3 root     root             4 Apr 24 20:08 ..
drwxrwxr-x   10 1001     1000            10 Oct  5 16:46 appdata
drwxrwxr-x    3 1001     1000             5 Oct  5 13:16 compose
drwxrwxr-x    2 1001     1000             2 Apr 25 00:58 scripts
drwxrwxr-x    2 1001     1000             2 Apr 25 00:58 secrets
drwxrwxr-x   13 1001     1000            14 Oct  5 16:38 stacks
# ls -al /share/docker/stacks/
drwxrwxr-x   13 1001     1000            14 Oct  5 16:38 .
drwxrwx---    9 1001     1000             9 Jul 27 13:10 ..
-rwxrwxr-x    1 1001     1000           117 Oct  5 11:55 .env.global
drwxrwxr-x    2 1001     1000             4 Oct 10 06:53 arcane
drwxrwxr-x    2 1001     1000             4 Sep 11 21:23 homepage
drwxrwxr-x    2 1001     1000             4 Sep 11 21:23 jellyfin
# ls -al /share/docker/stacks/arcane/
drwxrwxr-x    2 1001     1000             4 Oct 10 06:53 .
drwxrwxr-x   13 1001     1000            14 Oct  5 16:38 ..
-rwxrwxr-x    1 1001     1000           457 Oct 10 00:03 .env
-rwxrwxr-x    1 1001     1000          2165 Oct 10 00:06 compose.yaml
```
```
Oct 12 14:23:31.319 INF Filesystem change detected, syncing projects
Oct 12 14:23:31.325 INF Project sync completed after filesystem change
Oct 12 14:24:01.327 INF Filesystem change detected, syncing projects
Oct 12 14:24:01.334 INF Project sync completed after filesystem change
Oct 12 14:24:07.903 WRN Failed to load project env path=data/projects/something/.env error="stat data/projects/something/.env: no such file or directory"
Oct 12 14:24:07.904 WRN Failed to load project env path=data/projects/something/.env error="stat data/projects/something/.env: no such file or directory"
```

<img width="1198" height="72" alt="Image" src="https://github.com/user-attachments/assets/b275eb1a-19ad-4d2c-b14f-d3f955b85cd4" />

**Comment by kmendell** [comment]
Oh most likley the issue is permissions yes, , i bet if you chnage the user to be root inside the container by using `user: root` it should fix that issue i think.

**Comment by languagegame** [comment]
I am using a UGREEN NAS with UGOS.  I am still getting an error upon startup of "ERR Filesystem watcher failed error="permission denied", and none of my existing stacks show up in the Projects tab of Arcane.

Here is my docker compose:
```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    restart: unless-stopped
    user: root:root # root user and group
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/arcane/data:/app/data
      - /volume1/docker:/volume1/docker
    environment:
      - APP_URL=https://arcane.example.com
      - PROJECTS_DIR=/volume1/docker
      - PUID=1000 # user in admin group
      - PGID=10 # admin group
      - DOCKER_GID=0 # root group
      - ANALYTICS_DISABLED=true
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
```
Upon initialization during first boot of the container, it creates a number of files in /volume1/docker/arcane/data, so it has write access there.  Initially, arcane still uses the default Projects Directory in the internal container, so it does not report a filesystem watcher error.  However, after I change the Projects Directory to /volume1/docker using arcane's UI, I then restart the container and get a Filesystem watcher failed error.  No existing stacks show up in arcane.

Here are the filesystem permissions for the relevant folders when I login as user 1000
```
/$ ls -lan
drwxr-xr-x   1 0 0 4096 Oct 14 17:01 .
drwxr-xr-x   1 0 0  4096 Oct 14 17:01 ..
drwxr-xr-x   1 0 0   238 Oct  5 19:30 volume1

/$ ls -lan ./volume1
drwxr-xr-x 1 0 0  238 Oct  5 19:30 .
drwxr-xr-x 1 0 0 4096 Oct 14 17:01 ..
drwx--x--- 1 0 0  154 Oct 14 17:01 @docker # this is another folder used by my OS
drwxrwxrwx 1 0 0  294 Oct 17 07:30 docker # my stacks are in this folder

/$ ls -lan ./volume1/docker
drwxrwxrwx 1 0      0  294 Oct 17 07:30 .
drwxr-xr-x 1 0      0  238 Oct  5 19:30 ..
drwxrwxrwx 1 1000 10  54 Oct 17 09:11 arcane
drwxrwxrwx 1 1000 10  68 Mar 19  2025 crafty
drwxrwxrwx 1 1000 10  30 Mar 15  2025 immich
drwxrwxrwx 1 1000 10  12 Oct 12 15:25 _restore
```

When I sudo su -, I see slightly different file permissions for the same folders
```
/$ ls -lan
drwxr-xr-x   1 0 0  4096 Oct 14 17:01 .
drwxr-xr-x   1 0 0  4096 Oct 14 17:01 ..
drwxr-xr-x   1 0 0   238 Oct  5 19:30 volume1

/$ ls -lan ./volume1
drwxr-xr-x 1 0 0  238 Oct  5 19:30 .
drwxr-xr-x 1 0 0 4096 Oct 14 17:01 ..
drwx--x--- 1 0 0  154 Oct 14 17:01 @docker
drwx------ 1 0 0  294 Oct 17 07:30 docker # this now shows different permissions than if I login as user 1000

/$ ls -lan ./volume1/docker
drwx------ 1    0  0 294 Oct 17 07:30 .
drwxr-xr-x 1    0  0 238 Oct  5 19:30 ..
drwxrwx--- 1 1000 10  54 Oct 17 09:41 arcane
drwxrwxrwx 1 1000 10  68 Mar 19  2025 crafty
drwxrwxrwx 1 1000 10  30 Mar 15  2025 immich
drwxrwx--- 1 1000 10  12 Oct 12 15:25 _restore
```

Here is the log from arcane's container upon a restart after configuring the Projects Directory to /volume1/docker
```
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=1000, PGID=10, DOCKER_GID=998
arcane  | Entrypoint: Group with GID 10 exists as 'wheel', using it...
arcane  | Entrypoint: User arcane already exists with UID 1000
arcane  | usermod: no changes
arcane  | Entrypoint: Docker socket found with GID 121
arcane  | Entrypoint: Docker socket configured (GID: 121)
arcane  | Entrypoint: Setting up data directory...
arcane  | Entrypoint: Detected bind-mounted projects at /volume1/docker; skipping recursive chown
arcane  | Entrypoint: Projects path used for GID detection: /volume1/docker/_restore (uid:1000 gid:10)
arcane  | Entrypoint: Setup complete. Starting as arcane (UID: 1000, GID: 10)
arcane  | Oct 17 16:33:07.367 INF Arcane is starting
arcane  | Oct 17 16:33:07.369 INF Database schema is up to date
arcane  | Oct 17 16:33:07.369 INF Database initialized successfully
arcane  | Oct 17 16:33:07.370 INF Ensuring default settings are initialized
arcane  | Oct 17 16:33:07.372 INF Default settings initialized successfully
arcane  | Oct 17 16:33:07.372 WRN Users already exist, skipping default admin creation
arcane  | Oct 17 16:33:07.372 INF auto-update disabled or polling disabled; job not registered autoUpdate=false pollingEnabled=true
arcane  | Oct 17 16:33:07.372 INF registering image polling job interval=1h0m0s
arcane  | Oct 17 16:33:07.372 INF Job registered successfully name=image-polling
arcane  | Oct 17 16:33:07.372 INF analytics disabled or not in production; heartbeat job not registered analyticsDisabled=true env=production
arcane  | Oct 17 16:33:07.372 INF Registering event cleanup job jobName=EventCleanup
arcane  | Oct 17 16:33:07.372 INF Job registered successfully name=EventCleanup
arcane  | Oct 17 16:33:07.372 INF Event cleanup job registered successfully jobName=EventCleanup interval=6h retention=36h
arcane  | Oct 17 16:33:07.372 INF Filesystem watcher job registered
arcane  | Oct 17 16:33:07.373 INF Starting scheduler
arcane  | Oct 17 16:33:07.373 INF Starting job scheduler
arcane  | Oct 17 16:33:07.373 INF Starting HTTP server port=3552
arcane  | Oct 17 16:33:07.373 ERR Filesystem watcher failed error="permission denied"
```

**Comment by languagegame** [comment]
I think the issue is that the UGREEN os applies a user-space ACL overlay to manage permissions of the Docker folder where I have my stacks installed.  I believe Synology NAS devices do this as well.  Essentially, the permissions reported when running as a NAS user (in this case UID=1000) show up differently than if listing permissions as sudo su -.  The su user sees the underlying filesystem permissions that docker uses, which in this case is 700, not 777.  This means when Arcane runs and tried to attach a filesystem watcher to the /volume1/docker directory, it fails as the root group does not have permission to read/write/execute the /volume1/docker folder.  Unfortunately, if I manually chmod the /volume1/docker folder to apply 770 or 750 permissions to allow the root group to access it for a filesystem watcher, the NAS OS resets it back to 700 in the underlying filesystem.  So I either need to use a different folder for Arcane than what the NAS uses for docker compose or come up with an alternative solution.

In this case, the docker container can read files in /volume1/docker after that has been mounted in the container.  Is there a way to have a backup capability for filesystem watcher that just does an ls in that directory within the container rather than trying to attach an inotify or whatever Arcane uses to /volume1/docker?  When I type ls /volume/docker1 in the Arcane container, I can see all the project folders and enter directories to see the compose files.   So the container can see them.  It's just that the filesystem watcher gets a permission denied when trying to attach to the /volume/docker1 folder itself,

**Comment by brikim** [comment]
@languagegame I had a similar issue in
https://github.com/ofkm/arcane/issues/732

My issue was in the arcane-headless for a remote machine so I don't know if these issues are the same.

@kmendell suggested setting in volumes
/volume1/docker:/volume1/docker

and setting the environment variable
PROJECTS_DIR=/volume/docker

I then also had to set environment variables
PUID={User ID that has permissions}
PGID={User group ID that has permissions}

This worked for me when I had similar issues.

**Comment by kmendell** [comment]
I will have to look into this more

**Comment by kmendell** [comment]
I just want to confirm is this still an issue or is it resolved now?

**Comment by wieluk** [comment]
I have the same problem but with:

```
Nov 13 14:56:24.557 ERR Filesystem watcher failed error="too many open files"
```

Is it trying to watch all files in my whole stack folder? It only needs docker-compose.yml and .env right?

**Comment by kmendell** [comment]
@wieluk It should only watch those files yes, can you try this image: `ghcr.io/getarcaneapp/arcane:fs-watcher` to see if this fixes the issue?

**Comment by wieluk** [comment]
Thanks. Yea `ghcr.io/getarcaneapp/arcane:fs-watcher` fixes my problem.

**Comment by kmendell** [comment]
@wieluk Awesome, thank you for testing :) im hoping to get a release published in the next day or so.... fingers crossed.

**Comment by languagegame** [comment]
My issue was solved by changing the directory ownership and permissions on UGREEN.  UGOS uses an overlay permissions system, whereas the docker container uses the underlying linux permissions.  So I had to SSH into the UGREEN and enter these commands:
```
sudo chown 1000:100 /volume1/docker
sudo chmod 770 /volume1/docker
```
where 1000:100 is the user and group that is running as the docker container.  This allows the container to use a filesystem watcher on the directory

**Comment by ghostviburnum** [comment]
I wanted to provide some feedback as well. I had mounted my docker folder similarly on my Synology - /volume1/docker:/volume1/docker. That was based on the instructions. But when I was doing some troubleshooting I noticed it instead should have been mounted as /volume1/docker:/app/volume1/docker. After I corrected this mount everything showed up perfectly. It could be an odd Synology issue, but I wanted to point it out in case it was an instruction/documentation issue that instead needed correcting. The instructions I’m referring to are in the purple box here: https://getarcane.app/docs/setup/installation

**Comment by ghostviburnum** [comment]
As a follow up, I quickly discovered that my workaround, while it would allow me to view the projects, would not work correctly when trying to modify or update containers due to the “non-symmetrical” mapping. Sorry about that. Regardless, I’m still unable to load my existing compose files when mapped properly and I couldn’t get fs-watcher version that you asked we try to fix the issue either.
