### ISSUE TITLE
🐞 Bug: private registry credentials (again) not correctly passed to agents

### ISSUE THREAD

**Issue by petrm** [getarcaneapp/arcane#837]
### Bug Description

When clicking the icon in the updates column on the images screen, with an agent node selected, the credentials of the private repository are not correctly passed through. Clicking the check updates button seems to work fine.

Screenshots:
<img width="394" height="85" alt="Image" src="https://github.com/user-attachments/assets/9c49b0af-4ff7-428b-b1c2-f5b6efe413eb" />

<img width="340" height="170" alt="Image" src="https://github.com/user-attachments/assets/7813dfd4-83a8-4952-a9ad-afa04572f871" /> 

### Steps To Reproduce

See description

### Expected Behavior

Credentials passed over correctly

### Actual Behavior

See description

### Arcane Version

v0.1.7.2

### Operating System

Linux

### Browser

N/A

### Docker Version

N/A

**Comment by kmendell** [comment]
This should be fixed here: https://github.com/getarcaneapp/arcane/commit/64cd997573777cc49ad27c9ca271f243f5ed9a41, can you test the `ghcr.io/getarcaneapp/arcane:next` image once thats done building?

**Comment by petrm** [comment]
I upgraded to 1.8.1 and I think it is not quite fixed:
 
<img width="548" height="594" alt="Image" src="https://github.com/user-attachments/assets/e8bb55eb-1267-4eae-9d34-db3f5c80494d" />

I don't get the notification in the corner anymore, but is still errors out.

**Comment by kmendell** [comment]
Do you have the credentials added in arcane it self?

**Comment by petrm** [comment]
Yes, I do have the credentials in place.
Clicking check updates on the images page works fine and checks for the updates.

The pull button on the project page now doesn't work either, used to work before.

<img width="1156" height="343" alt="Image" src="https://github.com/user-attachments/assets/b40e0269-6318-4db5-ac95-fca50e9dfd9d" />

**Comment by kmendell** [comment]
Okay i will look at that once i get home

**Comment by petrm** [comment]
Hey @kmendell 
This is a cursed issue. I am now on 1.9.0 and I found another place where this is failing: on the project page clicking on "pull".
Interestingly on the same page "redeploy" works just fine and pulls the latest image from a private repo.
